#   to set up env values
#   $ source setEnvSample.sh
export MESSENGER_APP_SECRET=YOUR_MESSENGER_APP_SECRET
echo 'set MESSENGER_APP_SECRET'
export MESSENGER_VALIDATION_TOKEN=YOUR_MESSENGER_VALIDATION_TOKEN
echo 'set MESSENGER_VALIDATION_TOKEN'
export SERVER_URL=YOUR_SERVER_URL
echo 'set SERVER_URL'
export MESSENGER_PAGE_ACCESS_TOKEN=YOUR_MESSENGER_PAGE_ACCESS_TOKEN
echo 'set MESSENGER_PAGE_ACCESS_TOKEN'
